// ps-1

let name = 'Sahil'
let num = 24;
let mixed = name+num
// console.log(mixed);

// ps-2
// console.log(typeof mixed);

//ps-3
 const obj = {
    Name : 'Sahil',
    Age : 20,
    Email : "www.Khola.com"
 }
//  let obj = "khola"
 
 //ps-4
 obj['friend']= 'Karan'
 obj['Age'] = '21'
//  console.log(obj);

// ps-5

 const dic = {
    appreciate : ' recogine the full wroth of',
    ataraxia : 'a state of freedom from emotion',
    yakka : 'hardwork'
 }
 console.log(dic.yakka);
 console.log(dic['appreciate']);
 